/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSanctumRouteImport } from './routes/_authenticated/sanctum'
import { Route as AuthenticatedOracleRouteImport } from './routes/_authenticated/oracle'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSanctumRoute = AuthenticatedSanctumRouteImport.update({
  id: '/sanctum',
  path: '/sanctum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOracleRoute = AuthenticatedOracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/oracle': typeof AuthenticatedOracleRoute
  '/sanctum': typeof AuthenticatedSanctumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/oracle': typeof AuthenticatedOracleRoute
  '/sanctum': typeof AuthenticatedSanctumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/oracle': typeof AuthenticatedOracleRoute
  '/_authenticated/sanctum': typeof AuthenticatedSanctumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/oracle' | '/sanctum'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/oracle' | '/sanctum'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/oracle'
    | '/_authenticated/sanctum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sanctum': {
      id: '/_authenticated/sanctum'
      path: '/sanctum'
      fullPath: '/sanctum'
      preLoaderRoute: typeof AuthenticatedSanctumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oracle': {
      id: '/_authenticated/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof AuthenticatedOracleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOracleRoute: typeof AuthenticatedOracleRoute
  AuthenticatedSanctumRoute: typeof AuthenticatedSanctumRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOracleRoute: AuthenticatedOracleRoute,
  AuthenticatedSanctumRoute: AuthenticatedSanctumRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
